# https://github.com/pdm-project/setup-pdm
# https://github.com/actions/checkout
# https://github.com/pypa/gh-action-pypi-publish

name: Publish to PyPI

on:
  push:
    branches:
      - main
    paths:
      - "src/nbadge/__init__.py"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          python-version: 3.7
          version: 2.0.3
      - name: Install dependencies
        run: pdm install
      - name: Build
        run: pdm build --no-isolation --verbose
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
          packages_dir: dist/
